function res = checkVarExistsFromInsideFun(varName)
    
%     res = exist(varName, 'var') == 1;

%     cmd = ;

    res = evalin ...
        ( 'base' ...
        , sprintf ...
            ( "exist('%s', 'var') == 1" ...
            , varName ...
            ) ...
        );
    
end